version: '3'

services:
  atv:
    build:
      context: .
      dockerfile: Dockerfile
    image: ros2-image
    container_name: ros2-container
    stdin_open: true
    network_mode: "bridge"

  # microros-serial:
  #   image: microros/micro-ros-agent:humble
  #   container_name: microros-serial-container
  #   tty: true
  #   privileged: true
  #   devices:
  #     - /dev/ttyUSB0:/dev/ttyUSB0
  #   command: serial --dev /dev/ttyUSB0
  #   network_mode: "bridge"

  # microros-udp:
  #   image: microros/micro-ros-agent:humble
  #   container_name: microros-udp-container
  #   tty: true
  #   privileged: true
  #   ports:
  #     - "8888:8888/udp"
  #   command: udp4 --port 8888
  #   network_mode: "bridge"
