version: '3'

services:
  atv:
    build:
      context: .
      dockerfile: Dockerfile
    image: ros2-image
    container_name: ros2-container
    # ports:
    #   - 11811:11811 # ROS2 DDS communication
    #   - 7400-7600:7400-7600 # multicat and unicast
    stdin_open: true
    # network_mode: "host"

  # microros-serial:
  #   image: microros/micro-ros-agent:humble
  #   container_name: microros-serial-container
  #   tty: true
  #   privileged: true
  #   devices:
  #     - /dev/ttyUSB0:/dev/ttyUSB0
  #   command: serial --dev /dev/ttyUSB0

  # microros-udp:
  #   image: microros/micro-ros-agent:humble
  #   container_name: microros-udp-container
  #   tty: true
  #   privileged: true
  #   ports:
  #     - "8888:8888/udp"
  #   command: udp4 --port 8888
